Auth tests
agtugchik/react-trainee-project pull request #4
Opened 2024-12-12 12:12 UTC by agtugchik

2024-12-17 07:58 UTC, alexlatypov requested changes

2024-12-17 07:58 UTC, alexlatypov commented on src/__tests__/index.test.js
> +    fireEvent.change(emailInput, { target: { value: notValidEmail } });
use userEvent instead of fireEvent

2024-12-19 07:54 UTC, agtugchik commented on src/__tests__/index.test.js
> +    fireEvent.change(emailInput, { target: { value: notValidEmail } });
fixed

2024-12-19 08:06 UTC, alexlatypov requested changes

2024-12-19 08:06 UTC, alexlatypov commented on src/components/ui/InputValidationError/InputValidationError.test.tsx
> +  it('should throw email error', () => {
I think u can combine all `it` to one

2024-12-19 09:34 UTC, agtugchik commented on src/components/ui/InputValidationError/InputValidationError.test.tsx
> +  it('should throw email error', () => {
fixed

2024-12-19 09:57 UTC, merged